"""init schema

Revision ID: bbf1d5b653fa
Revises: 
Create Date: 2026-09-17 22:47:36.525802

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bbf1d5b653fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispense_stations',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('line', sa.String(length=120), nullable=False),
    sa.Column('dispenser_class', sa.Enum('PRESSURE_TIME', 'AUGER', 'PISTON', 'JETTING', name='dispenser_class', native_enum=False), nullable=False),
    sa.Column('valve_model', sa.String(length=120), nullable=True),
    sa.Column('heated_reservoir', sa.Boolean(), nullable=False),
    sa.Column('reports_dispense_order', sa.Boolean(), nullable=False),
    sa.Column('camera_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('fluid_materials',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('part_number', sa.String(length=120), nullable=True),
    sa.Column('family', sa.Enum('EPOXY', 'SOLDER_PASTE', 'SILICONE', 'UV_CURE', 'CYANOACRYLATE', name='material_family', native_enum=False), nullable=False),
    sa.Column('two_part', sa.Boolean(), nullable=False),
    sa.Column('thixotropic', sa.Boolean(), nullable=False),
    sa.Column('requires_thaw', sa.Boolean(), nullable=False),
    sa.Column('pot_life_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('out_time_hours', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('storage_temp_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('filler_particle_um', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('dispense_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('needle_gauge', sa.String(length=20), nullable=True),
    sa.Column('needle_id_um', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('set_pressure_kpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('set_time_ms', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('standoff_um', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('speed_mm_s', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('set_temp_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('spec_metric', sa.String(length=60), nullable=True),
    sa.Column('spec_limit', sa.String(length=60), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['fluid_materials.material_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('cases',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('rules_version', sa.String(length=60), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('material_lot', sa.String(length=60), nullable=True),
    sa.Column('complaint', sa.String(length=120), nullable=True),
    sa.Column('complaint_text', sa.Text(), nullable=True),
    sa.Column('fingerprint', sa.JSON(), nullable=True),
    sa.Column('pre_intake_actions', sa.JSON(), nullable=True),
    sa.Column('vision_result', sa.JSON(), nullable=True),
    sa.Column('ranking', sa.JSON(), nullable=True),
    sa.Column('rank_tier', sa.Enum('T1', 'T2', 'T3', 'T4', name='rank_tier', native_enum=False), nullable=True),
    sa.Column('llm_map_used', sa.Boolean(), nullable=False),
    sa.Column('llm_critic_used', sa.Boolean(), nullable=False),
    sa.Column('llm_explain_used', sa.Boolean(), nullable=False),
    sa.Column('diagnosis', sa.JSON(), nullable=True),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('diagnosed', sa.Enum('CHECK_CONFIRMED', 'BEST_GUESS', 'NEVER_TESTED', name='diagnosed_state', native_enum=False), nullable=False),
    sa.Column('tier', sa.Enum('CONFIRMED', 'PLAUSIBLE', 'UNVERIFIED', name='case_tier', native_enum=False), nullable=True),
    sa.Column('escalate', sa.Boolean(), nullable=False),
    sa.Column('engineer_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['dispense_profiles.profile_id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['dispense_stations.station_id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('check_results',
    sa.Column('check_result_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=120), nullable=False),
    sa.Column('cause_id', sa.String(length=60), nullable=True),
    sa.Column('cost_minutes', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('invasive', sa.Boolean(), nullable=False),
    sa.Column('safety_note', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Enum('CONFIRMS', 'RULES_OUT', 'INCONCLUSIVE', name='check_outcome', native_enum=False), nullable=True),
    sa.Column('result_detail', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], ),
    sa.PrimaryKeyConstraint('check_result_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_results')
    op.drop_table('cases')
    op.drop_table('dispense_profiles')
    op.drop_table('fluid_materials')
    op.drop_table('dispense_stations')
    # ### end Alembic commands ###
